version: "3"

services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa@
      MYSQL_DATABASE: gomworker
      MYSQL_USER: workers_usr
      MYSQL_PASSWORD: workers_pwd
    volumes:
      - ./migrations/gomworker.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
